In [3]:
import pandas as pd
import numpy as np

mp5=np.arange(25,50).reshape(5,5)
print(mp5)
df1=pd.DataFrame(mp5,index=['a','b','c','d','e'],columns=['A','B','C','D','E'])
print(df1)

[[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
    A   B   C   D   E
a  25  26  27  28  29
b  30  31  32  33  34
c  35  36  37  38  39
d  40  41  42  43  44
e  45  46  47  48  49
