In [1]:
import pandas as pd
import numpy as np

mp5=np.arange(25,50).reshape(5,5)
print(mp5)
df1=pd.DataFrame(mp5,index=['a','b','c','d','e'],columns=['A','B','C','D','E'])
print(df1)
print('hello world how are you ')

[[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
    A   B   C   D   E
a  25  26  27  28  29
b  30  31  32  33  34
c  35  36  37  38  39
d  40  41  42  43  44
e  45  46  47  48  49
hello world how are you 


In [2]:
l2=[[1,2,3],[44,55,66],[7,8,9]]
df2=pd.DataFrame(l2,index=['r1','r2','r3'],columns=['c1','c2','c3'])
print(df2)

    c1  c2  c3
r1   1   2   3
r2  44  55  66
r3   7   8   9


In [3]:
ld1=[{'Name':'Amit','Age':22,'City':'Delhi'},
     {'Name':'Sumit','Age':25,'City':'Mumbai'},
     {'Name':'Rohit','Age':24,'City':'Chennai'}]

df3=pd.DataFrame(ld1)
print(df3)

    Name  Age     City
0   Amit   22    Delhi
1  Sumit   25   Mumbai
2  Rohit   24  Chennai


In [4]:
dl1={'Name':['Amit','Sumit','Rohit'],
     'Age':[22,25,24],
     'City':['Delhi','Mumbai','Chennai']}
df4=pd.DataFrame(dl1)
print(df4)

    Name  Age     City
0   Amit   22    Delhi
1  Sumit   25   Mumbai
2  Rohit   24  Chennai


In [5]:
df4=pd.read_csv(r'/Users/algo trading 2026/batch 37/11_pandas/sp500.csv')
print(df4)

                           Name                  Sector   Price    EPS
0                     Apple Inc  Information Technology  170.12   9.20
1                    Abbvie Inc             Health Care   93.29   5.31
2           Abbott Laboratories             Health Care   55.28   2.41
3                 Accenture Plc  Information Technology  145.30    NaN
4                  Allergan Plc             Health Care  171.81  15.42
..                          ...                     ...     ...    ...
97   Verizon Communications Inc      Telecommunications   45.85   3.75
98     Walgreens Boots Alliance        Consumer Staples   70.25   5.10
99        Wells Fargo & Company              Financials   54.02   4.14
100             Wal-Mart Stores        Consumer Staples   96.08   4.36
101            Exxon Mobil Corp                  Energy   80.31   3.56

[102 rows x 4 columns]


In [6]:
!pip install lxml

In [7]:
!pip install --upgrade certifi

In [8]:
import os, certifi
# Set SSL certificate path for macOS
os.environ['SSL_CERT_FILE'] = certifi.where()
os.environ['REQUESTS_CA_BUNDLE'] = certifi.where()


In [13]:
!pip install requests

  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
  Using cached charset_normalizer-3.4.7-cp313-cp313-macosx_10_13_universal2.whl.metadata (40 kB)
  Using cached idna-3.18-py3-none-any.whl.metadata (6.1 kB)
  Using cached urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Using cached requests-2.34.2-py3-none-any.whl (73 kB)
Using cached charset_normalizer-3.4.7-cp313-cp313-macosx_10_13_universal2.whl (309 kB)
Using cached idna-3.18-py3-none-any.whl (65 kB)
Using cached urllib3-2.7.0-py3-none-any.whl (131 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [requests]


In [18]:
import requests

resp = requests.get("https://www.screener.in/company/NIFTY/", headers={"User-Agent": "Mozilla/5.0"})
resp.text

'\n<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1">\n\n    \n    <title>\n  Nifty 50 value and PE ratio | Constituents of Nifty 50\n - Screener</title>\n    \n\n    <!-- plausible -->\n    <script defer\n            event-user="unregistered"\n            \n            \n            data-domain="screener.in"\n            src="https://plausible.screener.in/js/script.pageview-props.tagged-events.js"></script>\n    <script>window.plausible = window.plausible || function () { (window.plausible.q = window.plausible.q || []).push(arguments) }</script>\n\n    <script src="https://rybbit.screener.in/api/script.js"\n            data-site-id="5494427e1dc0"\n            defer></script>\n\n    <!-- FONT -->\n    <link rel="stylesheet" href="https://cdn-static.screener.in/inter/inter.bccd7465af74.css?v=2" />\n    <link rel="stylesheet" href="https://cdn-static.screener.in/fontello/css/fontello.835ae8880a

In [20]:
import requests
import pandas as pd
from io import StringIO

url = "https://www.screener.in/company/NIFTY/"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)"}

resp = requests.get(url, headers=headers, timeout=10)
resp.raise_for_status()

tables = pd.read_html(StringIO(resp.text))   # returns a LIST of DataFrames
tables[0]

,S.No.,Name,CMP Rs.,P/E,Mar Cap Rs.Cr.,Div Yld %,NP Qtr Rs.Cr.,Qtr Profit Var %,Sales Qtr Rs.Cr.,Qtr Sales Var %,ROCE %
0,1.,Reliance Industries,1293.00,22.47,1749756.77,0.46,20589.00,-12.55,294059.00,12.50,10.26
1,2.,HDFC Bank,772.45,15.64,1189391.41,1.68,21074.22,8.05,87182.50,0.46,7.04
2,3.,Bharti Airtel,1822.50,38.67,1110500.17,0.88,9247.40,-16.49,55383.20,15.68,18.50
3,4.,ICICI Bank,1340.80,17.74,961620.51,0.82,15680.64,9.28,49593.75,2.49,7.20
4,5.,SBI,1017.15,11.27,938892.27,1.71,20507.98,0.22,131080.12,3.34,6.13
5,6.,TCS,2161.40,14.95,782013.44,2.96,13784.00,12.22,70698.00,9.65,63.03
6,7.,Bajaj Finance,918.30,29.76,571729.38,0.59,5553.30,21.99,21605.79,18.10,10.82
7,8.,Larsen & Toubro,4049.30,33.95,557074.02,0.94,6133.06,2.11,82762.16,11.25,14.57
8,9.,Hind. Unilever,2168.80,33.46,509579.35,1.89,2994.00,8.62,16351.00,7.64,28.42
9,10.,Infosys,1116.40,15.06,452952.05,4.30,8509.00,20.87,46402.00,13.38,39.95


In [9]:
df6=pd.read_html('https://www.screener.in/company/NIFTY/')
df6

[    S.No.                 Name  CMP  Rs.    P/E  Mar Cap  Rs.Cr.  Div Yld  %  \
 0      1.  Reliance Industries   1293.00  22.47       1749756.77        0.46   
 1      2.            HDFC Bank    772.45  15.64       1189391.41        1.68   
 2      3.        Bharti Airtel   1822.50  38.67       1110500.17        0.88   
 3      4.           ICICI Bank   1340.80  17.74        961620.51        0.82   
 4      5.                  SBI   1017.15  11.27        938892.27        1.71   
 5      6.                  TCS   2161.40  14.95        782013.44        2.96   
 6      7.        Bajaj Finance    918.30  29.76        571729.38        0.59   
 7      8.      Larsen & Toubro   4049.30  33.95        557074.02        0.94   
 8      9.       Hind. Unilever   2168.80  33.46        509579.35        1.89   
 9     10.              Infosys   1116.40  15.06        452952.05        4.30   
 10    11.     Sun Pharma.Inds.   1807.70  34.76        433727.78        0.89   
 11    12.            Axis B

In [ ]:
df6[0]
#request,selenium

,S.No.,Name,CMP Rs.,P/E,Mar Cap Rs.Cr.,Div Yld %,NP Qtr Rs.Cr.,Qtr Profit Var %,Sales Qtr Rs.Cr.,Qtr Sales Var %,ROCE %
0,1.,Reliance Industries,1293.00,22.47,1749756.77,0.46,20589.00,-12.55,294059.00,12.50,10.26
1,2.,HDFC Bank,772.45,15.64,1189391.41,1.68,21074.22,8.05,87182.50,0.46,7.04
2,3.,Bharti Airtel,1822.50,38.67,1110500.17,0.88,9247.40,-16.49,55383.20,15.68,18.50
3,4.,ICICI Bank,1340.80,17.74,961620.51,0.82,15680.64,9.28,49593.75,2.49,7.20
4,5.,SBI,1017.15,11.27,938892.27,1.71,20507.98,0.22,131080.12,3.34,6.13
5,6.,TCS,2161.40,14.95,782013.44,2.96,13784.00,12.22,70698.00,9.65,63.03
6,7.,Bajaj Finance,918.30,29.76,571729.38,0.59,5553.30,21.99,21605.79,18.10,10.82
7,8.,Larsen & Toubro,4049.30,33.95,557074.02,0.94,6133.06,2.11,82762.16,11.25,14.57
8,9.,Hind. Unilever,2168.80,33.46,509579.35,1.89,2994.00,8.62,16351.00,7.64,28.42
9,10.,Infosys,1116.40,15.06,452952.05,4.30,8509.00,20.87,46402.00,13.38,39.95


In [22]:
!pip install openpyxl

  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]


In [23]:
df7=pd.read_excel('/Users/algo trading 2026/batch 37/11_pandas/e500.xlsx')
df7

,Unnamed: 0,Name,Sector,Price,EPS
0,0,Apple Inc,Information Technology,170.12,9.20
1,1,Abbvie Inc,Health Care,93.29,5.31
2,2,Abbott Laboratories,Health Care,55.28,2.41
3,3,Accenture Plc,Information Technology,145.30,NaN
4,4,Allergan Plc,Health Care,171.81,15.42
...,...,...,...,...,...
97,97,Verizon Communications Inc,Telecommunications,45.85,3.75
98,98,Walgreens Boots Alliance,Consumer Staples,70.25,5.10
99,99,Wells Fargo & Company,Financials,54.02,4.14
100,100,Wal-Mart Stores,Consumer Staples,96.08,4.36


In [25]:
df4.shape

(102, 4)

In [28]:
list(df4.columns)

['Name', 'Sector', 'Price', 'EPS']

In [29]:
list(df4.index)

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101]

In [32]:
df4.head(10)

,Name,Sector,Price,EPS
0,Apple Inc,Information Technology,170.12,9.20
1,Abbvie Inc,Health Care,93.29,5.31
2,Abbott Laboratories,Health Care,55.28,2.41
3,Accenture Plc,Information Technology,145.30,NaN
4,Allergan Plc,Health Care,171.81,15.42
5,American International Group,Financials,59.50,2.51
6,Allstate Corp,Financials,100.50,6.79
7,Amgen,Health Care,168.93,12.58
8,Amazon.Com Inc.,Consumer Discretionary,1126.82,3.94
9,American Express Company,Financials,93.92,5.22


In [34]:
df4.tail(8)

,Name,Sector,Price,EPS
94,U.S. Bancorp,Financials,51.88,3.37
95,United Technologies Corp,Industrials,117.05,6.62
96,Visa Inc,Information Technology,110.27,3.48
97,Verizon Communications Inc,Telecommunications,45.85,3.75
98,Walgreens Boots Alliance,Consumer Staples,70.25,5.10
99,Wells Fargo & Company,Financials,54.02,4.14
100,Wal-Mart Stores,Consumer Staples,96.08,4.36
101,Exxon Mobil Corp,Energy,80.31,3.56


In [35]:
df4.info()

<class 'pandas.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    102 non-null    str    
 1   Sector  102 non-null    str    
 2   Price   102 non-null    float64
 3   EPS     101 non-null    float64
dtypes: float64(2), str(2)
memory usage: 3.3 KB


In [36]:
df4.describe()

,Price,EPS
count,102.000000,101.00000
mean,150.500686,6.49099
std,240.768463,8.62033
min,12.110000,0.02000
25%,54.335000,2.87000
50%,88.295000,4.36000
75%,151.032500,6.62000
max,1762.230000,74.45000


subsetting

In [38]:
df4.EPS

0       9.20
1       5.31
2       2.41
3        NaN
4      15.42
       ...  
97      3.75
98      5.10
99      4.14
100     4.36
101     3.56
Name: EPS, Length: 102, dtype: float64

In [41]:
df4['Name']

0                       Apple Inc
1                      Abbvie Inc
2             Abbott Laboratories
3                   Accenture Plc
4                    Allergan Plc
                  ...            
97     Verizon Communications Inc
98       Walgreens Boots Alliance
99          Wells Fargo & Company
100               Wal-Mart Stores
101              Exxon Mobil Corp
Name: Name, Length: 102, dtype: str

In [42]:
df4[['Name','Price']]

,Name,Price
0,Apple Inc,170.12
1,Abbvie Inc,93.29
2,Abbott Laboratories,55.28
3,Accenture Plc,145.30
4,Allergan Plc,171.81
...,...,...
97,Verizon Communications Inc,45.85
98,Walgreens Boots Alliance,70.25
99,Wells Fargo & Company,54.02
100,Wal-Mart Stores,96.08


In [48]:
df4[df4['Price']>100]

,Name,Sector,Price,EPS
0,Apple Inc,Information Technology,170.12,9.20
3,Accenture Plc,Information Technology,145.30,NaN
4,Allergan Plc,Health Care,171.81,15.42
6,Allstate Corp,Financials,100.50,6.79
7,Amgen,Health Care,168.93,12.58
8,Amazon.Com Inc.,Consumer Discretionary,1126.82,3.94
10,Boeing Company,Industrials,265.04,9.75
12,Biogen Inc,Health Care,311.92,21.59
14,Blackrock,Financials,474.05,21.55
16,Berkshire Hath Hld B,Financials,181.27,6.29


In [51]:
df4[df4['EPS']>10]

,Name,Sector,Price,EPS
4,Allergan Plc,Health Care,171.81,15.42
7,Amgen,Health Care,168.93,12.58
12,Biogen Inc,Health Care,311.92,21.59
14,Blackrock,Financials,474.05,21.55
37,Fedex Corp,Industrials,217.75,11.91
40,General Dynamics Corp,Industrials,198.70,10.07
44,Alphabet Class C,Information Technology,1018.48,29.87
45,Alphabet Class A,Information Technology,1034.09,29.87
46,Goldman Sachs Group,Financials,238.05,19.20
50,International Business Machines,Information Technology,151.40,13.66


In [54]:
a=df4['EPS']>10
b=df4['Price']>500
df4[a & b]['Name'].to_list()

['Alphabet Class C', 'Alphabet Class A', 'Priceline Group']