In [3]:
import pandas as pd
import numpy as np

mp5=np.arange(25,50).reshape(5,5)
print(mp5)
df1=pd.DataFrame(mp5,index=['a','b','c','d','e'],columns=['A','B','C','D','E'])
print(df1)

[[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
    A   B   C   D   E
a  25  26  27  28  29
b  30  31  32  33  34
c  35  36  37  38  39
d  40  41  42  43  44
e  45  46  47  48  49


In [6]:
l2=[[1,2,3],[44,55,66],[7,8,9]]
df2=pd.DataFrame(l2,index=['r1','r2','r3'],columns=['c1','c2','c3'])
print(df2)

    c1  c2  c3
r1   1   2   3
r2  44  55  66
r3   7   8   9


In [7]:
ld1=[{'Name':'Amit','Age':22,'City':'Delhi'},
     {'Name':'Sumit','Age':25,'City':'Mumbai'},
     {'Name':'Rohit','Age':24,'City':'Chennai'}]

df3=pd.DataFrame(ld1)
print(df3)

    Name  Age     City
0   Amit   22    Delhi
1  Sumit   25   Mumbai
2  Rohit   24  Chennai


In [8]:
dl1={'Name':['Amit','Sumit','Rohit'],
     'Age':[22,25,24],
     'City':['Delhi','Mumbai','Chennai']}
df4=pd.DataFrame(dl1)
print(df4)

    Name  Age     City
0   Amit   22    Delhi
1  Sumit   25   Mumbai
2  Rohit   24  Chennai


In [11]:
df4=pd.read_csv(r'/Users/algo trading 2026/batch 37/11_pandas/sp500.csv')
print(df4)

                           Name                  Sector   Price    EPS
0                     Apple Inc  Information Technology  170.12   9.20
1                    Abbvie Inc             Health Care   93.29   5.31
2           Abbott Laboratories             Health Care   55.28   2.41
3                 Accenture Plc  Information Technology  145.30    NaN
4                  Allergan Plc             Health Care  171.81  15.42
..                          ...                     ...     ...    ...
97   Verizon Communications Inc      Telecommunications   45.85   3.75
98     Walgreens Boots Alliance        Consumer Staples   70.25   5.10
99        Wells Fargo & Company              Financials   54.02   4.14
100             Wal-Mart Stores        Consumer Staples   96.08   4.36
101            Exxon Mobil Corp                  Energy   80.31   3.56

[102 rows x 4 columns]


In [ ]:
df6=pd.read_html()

In [12]:
df7=pd.read_excel()

TypeError: read_excel() missing 1 required positional argument: 'io'